/* Generated by Preqorsor 0.45.52 (git sha1 df1f848ed, c++ 15.0.0 -fPIC -O3) */

(* leakage_power_unit = "1pW" *)
(* LeakagePower = "0" *)
(* area = "0" *)
(* blackbox =  1  *)
module test1(TST, TST2, TST3);
  input TST;
  wire TST;
  input TST2;
  wire TST2;
  input TST3;
  wire TST3;
endmodule
