/* Generated by Preqorsor 0.45.52 (git sha1 df1f848ed, c++ 15.0.0 -fPIC -O3) */

(* leakage_power_unit = "1pW" *)
(* LeakagePower = "0" *)
(* area = "2" *)
(* blackbox =  1  *)
module AN2(A, B, D, E, Z);
  input A;
  wire A;
  input B;
  wire B;
  input [15:0] D;
  wire [15:0] D;
  input [31:0] E;
  wire [31:0] E;
  output Z;
  wire Z;
endmodule

(* leakage_power_unit = "1pW" *)
(* LeakagePower = "0" *)
(* area = "2" *)
(* blackbox =  1  *)
module OR2(A, B, Z);
  input A;
  wire A;
  input B;
  wire B;
  output Z;
  wire Z;
endmodule
