/* Generated by Preqorsor 0.47.6 (git sha1 2ae7490ad, ccache g++ 11.4.0-1ubuntu1~22.04 -fPIC -O3) */

(* leakage_power_unit = "1pW" *)
(* LeakagePower = "0" *)
(* area = "2" *)
(* blackbox =  1  *)
module AN2(A, B, X, Z);
  input A;
  wire A;
  input B;
  wire B;
  input X;
  wire X;
  output Z;
  wire Z;
endmodule

(* leakage_power_unit = "1pW" *)
(* LeakagePower = "0" *)
(* area = "2" *)
(* blackbox =  1  *)
module OR2(A, B, Z);
  input A;
  wire A;
  input B;
  wire B;
  output Z;
  wire Z;
endmodule
