/* Generated by Preqorsor 0.45.52 (git sha1 df1f848ed, c++ 15.0.0 -fPIC -O3) */

(* leakage_power_unit = "1pW" *)
(* LeakagePower = "0" *)
(* area = "2" *)
(* blackbox =  1  *)
module AN2(A, B, P);
  input A;
  wire A;
  input B;
  wire B;
  input P;
  wire P;
endmodule
