/* Generated by Preqorsor 0.47.6 (git sha1 2ae7490ad, ccache g++ 11.4.0-1ubuntu1~22.04 -fPIC -O3) */

(* leakage_power_unit = "1pW" *)
(* LeakagePower = "0" *)
(* area = "2" *)
(* memory =  1  *)
(* blackbox =  1  *)
module AN2(A, B, Z, D, E, H01, H02, H03, H04, CR0, CR1, LD0, LD1, D0, D1, Q0, Q1, Q3, QN0, QN1);
  input A;
  wire A;
  input B;
  wire B;
  input CR0;
  wire CR0;
  input CR1;
  wire CR1;
  input [15:0] D;
  wire [15:0] D;
  input D0;
  wire D0;
  input D1;
  wire D1;
  input [31:0] E;
  wire [31:0] E;
  input H01;
  wire H01;
  input H02;
  wire H02;
  input H03;
  wire H03;
  input H04;
  wire H04;
  input LD0;
  wire LD0;
  input LD1;
  wire LD1;
  output Q0;
  wire Q0;
  output Q1;
  wire Q1;
  output Q3;
  wire Q3;
  output QN0;
  wire QN0;
  output QN1;
  wire QN1;
  output Z;
  wire Z;
endmodule

(* leakage_power_unit = "1pW" *)
(* LeakagePower = "0" *)
(* area = "2" *)
(* blackbox =  1  *)
module OR2(A, B, Z);
  input A;
  wire A;
  input B;
  wire B;
  output Z;
  wire Z;
endmodule

(* leakage_power_unit = "1pW" *)
(* LeakagePower = "0" *)
(* area = "0" *)
(* blackbox =  1  *)
module bank33(SE, CK, Q0, Q1, Q2, Q3);
  input CK;
  wire CK;
  output Q0;
  wire Q0;
  output Q1;
  wire Q1;
  output Q2;
  wire Q2;
  output Q3;
  wire Q3;
  input SE;
  wire SE;
endmodule
