/* Generated by Preqorsor 0.45.52 (git sha1 df1f848ed, c++ 15.0.0 -fPIC -O3) */

(* leakage_power_unit = "1pW" *)
(* LeakagePower = "0" *)
(* area = "0" *)
(* blackbox =  1  *)
module ex(\Q[0] );
  input \Q[0] ;
  wire \Q[0] ;
endmodule
