/* Generated by Preqorsor 0.47.5 (git sha1 da726a4e5, ccache c++ 15.0.0 -fPIC -O3) */

(* leakage_power_unit = "1pW" *)
(* LeakagePower = "0" *)
(* area = "2" *)
(* blackbox =  1  *)
module AN2(A, B, X, Z);
  input A;
  wire A;
  input B;
  wire B;
  input X;
  wire X;
  output Z;
  wire Z;
endmodule

(* leakage_power_unit = "1pW" *)
(* LeakagePower = "0" *)
(* area = "2" *)
(* blackbox =  1  *)
module OR2(A, B, Z);
  input A;
  wire A;
  input B;
  wire B;
  output Z;
  wire Z;
endmodule
