/* Generated by Preqorsor 0.47.6 (git sha1 2ae7490ad, ccache g++ 11.4.0-1ubuntu1~22.04 -fPIC -O3) */

(* leakage_power_unit = "1pW" *)
(* LeakagePower = "0" *)
(* area = "1" *)
(* blackbox =  1  *)
module INV(A, Y);
  input A;
  wire A;
  output Y;
  wire Y;
endmodule
