/* Generated by Preqorsor 0.47.6 (git sha1 2ae7490ad, ccache g++ 11.4.0-1ubuntu1~22.04 -fPIC -O3) */

(* leakage_power_unit = "1pW" *)
(* LeakagePower = "0" *)
(* area = "0" *)
(* blackbox =  1  *)
module AND2X1(A, B, Y);
  input A;
  wire A;
  input B;
  wire B;
  output Y;
  wire Y;
endmodule
