/* Generated by Preqorsor 0.47.5 (git sha1 da726a4e5, ccache c++ 15.0.0 -fPIC -O3) */

(* leakage_power_unit = "1pW" *)
(* LeakagePower = "0" *)
(* area = "0" *)
(* blackbox =  1  *)
module AND2X1(A, B, Y);
  input A;
  wire A;
  input B;
  wire B;
  output Y;
  wire Y;
endmodule
