/* Generated by Preqorsor 0.47.5 (git sha1 da726a4e5, ccache c++ 15.0.0 -fPIC -O3) */

(* leakage_power_unit = "1pW" *)
(* LeakagePower = "0" *)
(* area = "12.0" *)
(* blackbox =  1  *)
module example();
endmodule
